### ISSUE TITLE
Not working on searches

### ISSUE THREAD

**Issue by tavinus** [cgzhang/Rayfox_Catalog#1]
Hi. Thanks for the extension.
I am using it on Magento CE 1.9.1 and it is working OK, except that it is doing nothing on searches. I didn't find anything on the logs that could point to where the problem is. Is there any tests I can make? It is enabled for searches on the backend of course.
EDIT: ~~I installed it from MagentoConnect. Is it the same version?~~ Yes, it is.
EDIT2: The backend doesn't seem to cause any effect in my install. I can set anything there and the catalog listings will always have out-of-stocks as last and searches will never have them. Cleared the caches and rebuilt indexes many times.

Ok, so my problem is that this extension conflicts with Smartwave_AjaxCatalog, since they both rewrite the same files. For searches the problem is worse because they rewrite the same method as well. In the end, I have incorporated most of the code from this extension into the Smartwave one, mostly because they change the prepareProductCollection($collection) in the search Layer file (they don't even use the parent one). So I had to make the sorting on the collection prepared by them.

I tried making one Class extend the other (instead of the Mage one), remove the rewrite, but could not make it work. Disabling their extension breaks my site. I was trying for hours and then just realised it would be easier to sort their collection.

**Comment by tavinus** [comment]
Ok mate, made a fix to the Jointable call and added support for Advanced searches. Tested on Magento CE 1.9.2. Pull request is available for you.

**Comment by razbakov** [comment]
Thank you!

**Comment by razbakov** [comment]
PR #2
