### ISSUE TITLE
Rayfox_Catalog Sorting issue

### ISSUE THREAD

**Issue by gautam-np** [cgzhang/Rayfox_Catalog#3]
This extension sorts the out of stock products after the in-stock products.
What changes should I make if I want to have out of stock products before the on-stock products.

**Comment by razbakov** [comment]
https://github.com/kirchbergerknorr/Rayfox_Catalog/blob/master/app/code/community/Rayfox/Catalog/Model/Layer.php#L34

try to change `desc` to `asc`
